language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master

after_success:
  - mvn clean test -Dgpg.skip
  - mvn clean cobertura:cobertura coveralls:report -Dgpg.skip
  - mvn license:check